### ISSUE TITLE
Code Maven?

### ISSUE THREAD

**Issue by haraldkubota** [glinden/code-monster-from-crunchzilla#1]
Hi Greg,

Not an issue, but I wonder if you plan to put Code Maven on GitHub too. For an introduction "course" Code Monster is fine, but in case of "Done that. Can I get more?" Code maven is IMHO perfect.

Any plans to share that code too?

Harald

PS: I'll work on the Japanese translation as I'm in Japan and thus targetting japanese children.

**Comment by glinden** [comment]
That's a great idea, Harald. Most of the demand was for Code Monster for Crunchzilla, but it's a good point that Code Maven and Game Maven might be worth open sourcing, especially at this point, so that others can use the content and build on them.

One concern I've had is that the images themselves might be used in ways that I don't like if I make all the content available, but I suppose that is already an issue. I probably should just go ahead with open sourcing all three. I don't think there's much demand for Stats Maven (which didn't attract the interest of the other three), but Code Maven and Game Maven have had some interest in translations or making variations of the content.

The code needs to be modified a bit in order to be ready to be made available here. I'll see if I can find some time to do that at some point. Thanks for the suggestion!

**Comment by glinden** [comment]
Okay, I went ahead and open sourced Code Maven too. It's at

https://github.com/glinden/code-maven-from-crunchzilla

**Comment by haraldkubota** [comment]
Awesome Greg! Thanks for creating this and open sourcing it. Hopefully in a
month from now it's available in German and Japanese. Me and 2 colleagues
are translating already!
Pull request coming in then!

Harald
